### ISSUE TITLE
ネットワークが悪すぎる

### ISSUE THREAD

**Issue by tannakaken** [peano-system/nugitlecture#1]
ES館のネットワークがあまりにもわるすぎる

**Comment by MasatakaHamada** [comment]
TortoiseGitの
Settings>Network
でプロキシサーバーの設定をすると解決するっぽいです。

参考
- [GitでProxyの設定を行ってエラー回避する方法](https://git-manual.net/git-proxy-error/)
- [コマンドプロンプトから現在のプロキシ設定を確認する (Windows Tips)](https://www.ipentec.com/document/windows-netsh-winhttp-show-proxy)
